name: Build and Publish

on:
  push:
    branches:
      - master
      - adopt*
      - test/*
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-adopt*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        IMAGE_ORG=pypeware
        IMAGE_NAME=bungeecord
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=${GITHUB_REF#refs/heads/}
          if [[ $VERSION == master ]]; then
            VERSION=latest
          fi
        fi
        TAGS="${IMAGE_ORG}/${IMAGE_NAME}:${VERSION//\//-}"
        echo ::set-output name=image_org::${IMAGE_ORG}
        echo ::set-output name=image_name::${IMAGE_NAME}
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=cache_from::${TAGS}
        echo ::set-output name=version::${VERSION//\//-}
        echo ::set-output name=cache_version::${VERSION//\//-}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ steps.prep.outputs.cache_version }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ steps.prep.outputs.cache_version }}-
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        # ensure latest base image is used
        pull: true
        # publish
        push: true
        # tags determined by prep step
        tags: ${{ steps.prep.outputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: |
          org.opencontainers.image.documentation=https://github.com/pypeware/docker-bungeecord
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.source=https://github.com/pypeware/docker-bungeecord
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
